java -jar engine/Tron.jar maps/u.txt ./MyTronBot ./MyTronBot 0
java -jar engine/Tron.jar maps/u.txt ./MyTronBot ./MyTronBot 0
java -jar engine/Tron.jar maps/apocalyptic.txt ./MyTronBot ./MyTronBot 0
java -jar engine/Tron.jar maps/big-room.txt ./MyTronBot ./MyTronBot 0
java -jar engine/Tron.jar maps/center.txt ./MyTronBot ./MyTronBot 0
java -jar engine/Tron.jar maps/divider.txt ./MyTronBot ./MyTronBot 0
java -jar engine/Tron.jar maps/empty-room.txt ./MyTronBot ./MyTronBot 0
java -jar engine/Tron.jar maps/huge-room.txt ./MyTronBot ./MyTronBot 0
java -jar engine/Tron.jar maps/joust.txt ./MyTronBot ./MyTronBot 0
java -jar engine/Tron.jar maps/keyhole.txt ./MyTronBot ./MyTronBot 0
java -jar engine/Tron.jar maps/playground.txt ./MyTronBot ./MyTronBot 0
java -jar engine/Tron.jar maps/quadrant.txt ./MyTronBot ./MyTronBot 0
java -jar engine/Tron.jar maps/ring.txt ./MyTronBot ./MyTronBot 0
java -jar engine/Tron.jar maps/test-board2.txt ./MyTronBot ./MyTronBot 0
java -jar engine/Tron.jar maps/test-board.txt ./MyTronBot ./MyTronBot 0
java -jar engine/Tron.jar maps/toronto.txt ./MyTronBot ./MyTronBot 0
java -jar engine/Tron.jar maps/trix.txt ./MyTronBot ./MyTronBot 0
java -jar engine/Tron.jar maps/u.txt ./MyTronBot ./MyTronBot 0
