java -jar engine/Tron.jar maps/apocalyptic.txt "./MyTronBot"  "java -jar example_bots/Chaser.jar" 0
java -jar engine/Tron.jar maps/apocalyptic.txt "./MyTronBot"  "java -jar example_bots/RandomBot.jar" 0
java -jar engine/Tron.jar maps/apocalyptic.txt "./MyTronBot"  "java -jar example_bots/RunAway.jar" 0
java -jar engine/Tron.jar maps/apocalyptic.txt "./MyTronBot"  "java -jar example_bots/WallHugger.jar" 0
java -jar engine/Tron.jar maps/big-room.txt "./MyTronBot"  "java -jar example_bots/Chaser.jar" 0
java -jar engine/Tron.jar maps/big-room.txt "./MyTronBot"  "java -jar example_bots/RandomBot.jar" 0
java -jar engine/Tron.jar maps/big-room.txt "./MyTronBot"  "java -jar example_bots/RunAway.jar" 0
java -jar engine/Tron.jar maps/big-room.txt "./MyTronBot"  "java -jar example_bots/WallHugger.jar" 0
java -jar engine/Tron.jar maps/center.txt "./MyTronBot"  "java -jar example_bots/Chaser.jar" 0
java -jar engine/Tron.jar maps/center.txt "./MyTronBot"  "java -jar example_bots/RandomBot.jar" 0
java -jar engine/Tron.jar maps/center.txt "./MyTronBot"  "java -jar example_bots/RunAway.jar" 0
java -jar engine/Tron.jar maps/center.txt "./MyTronBot"  "java -jar example_bots/WallHugger.jar" 0
java -jar engine/Tron.jar maps/divider.txt "./MyTronBot"  "java -jar example_bots/Chaser.jar" 0
java -jar engine/Tron.jar maps/divider.txt "./MyTronBot"  "java -jar example_bots/RandomBot.jar" 0
java -jar engine/Tron.jar maps/divider.txt "./MyTronBot"  "java -jar example_bots/RunAway.jar" 0
java -jar engine/Tron.jar maps/divider.txt "./MyTronBot"  "java -jar example_bots/WallHugger.jar" 0
java -jar engine/Tron.jar maps/empty-room.txt "./MyTronBot"  "java -jar example_bots/Chaser.jar" 0
java -jar engine/Tron.jar maps/empty-room.txt "./MyTronBot"  "java -jar example_bots/RandomBot.jar" 0
java -jar engine/Tron.jar maps/empty-room.txt "./MyTronBot"  "java -jar example_bots/RunAway.jar" 0
java -jar engine/Tron.jar maps/empty-room.txt "./MyTronBot"  "java -jar example_bots/WallHugger.jar" 0
java -jar engine/Tron.jar maps/huge-room.txt "./MyTronBot"  "java -jar example_bots/Chaser.jar" 0
java -jar engine/Tron.jar maps/huge-room.txt "./MyTronBot"  "java -jar example_bots/RandomBot.jar" 0
java -jar engine/Tron.jar maps/huge-room.txt "./MyTronBot"  "java -jar example_bots/RunAway.jar" 0
java -jar engine/Tron.jar maps/huge-room.txt "./MyTronBot"  "java -jar example_bots/WallHugger.jar" 0
java -jar engine/Tron.jar maps/joust.txt "./MyTronBot"  "java -jar example_bots/Chaser.jar" 0
java -jar engine/Tron.jar maps/joust.txt "./MyTronBot"  "java -jar example_bots/RandomBot.jar" 0
java -jar engine/Tron.jar maps/joust.txt "./MyTronBot"  "java -jar example_bots/RunAway.jar" 0
java -jar engine/Tron.jar maps/joust.txt "./MyTronBot"  "java -jar example_bots/WallHugger.jar" 0
java -jar engine/Tron.jar maps/keyhole.txt "./MyTronBot"  "java -jar example_bots/Chaser.jar" 0
java -jar engine/Tron.jar maps/keyhole.txt "./MyTronBot"  "java -jar example_bots/RandomBot.jar" 0
java -jar engine/Tron.jar maps/keyhole.txt "./MyTronBot"  "java -jar example_bots/RunAway.jar" 0
java -jar engine/Tron.jar maps/keyhole.txt "./MyTronBot"  "java -jar example_bots/WallHugger.jar" 0
java -jar engine/Tron.jar maps/playground.txt "./MyTronBot"  "java -jar example_bots/Chaser.jar" 0
java -jar engine/Tron.jar maps/playground.txt "./MyTronBot"  "java -jar example_bots/RandomBot.jar" 0
java -jar engine/Tron.jar maps/playground.txt "./MyTronBot"  "java -jar example_bots/RunAway.jar" 0
java -jar engine/Tron.jar maps/playground.txt "./MyTronBot"  "java -jar example_bots/WallHugger.jar" 0
java -jar engine/Tron.jar maps/quadrant.txt "./MyTronBot"  "java -jar example_bots/Chaser.jar" 0
java -jar engine/Tron.jar maps/quadrant.txt "./MyTronBot"  "java -jar example_bots/RandomBot.jar" 0
java -jar engine/Tron.jar maps/quadrant.txt "./MyTronBot"  "java -jar example_bots/RunAway.jar" 0
java -jar engine/Tron.jar maps/quadrant.txt "./MyTronBot"  "java -jar example_bots/WallHugger.jar" 0
java -jar engine/Tron.jar maps/ring.txt "./MyTronBot"  "java -jar example_bots/Chaser.jar" 0
java -jar engine/Tron.jar maps/ring.txt "./MyTronBot"  "java -jar example_bots/RandomBot.jar" 0
java -jar engine/Tron.jar maps/ring.txt "./MyTronBot"  "java -jar example_bots/RunAway.jar" 0
java -jar engine/Tron.jar maps/ring.txt "./MyTronBot"  "java -jar example_bots/WallHugger.jar" 0
java -jar engine/Tron.jar maps/test-board2.txt "./MyTronBot"  "java -jar example_bots/Chaser.jar" 0
java -jar engine/Tron.jar maps/test-board2.txt "./MyTronBot"  "java -jar example_bots/RandomBot.jar" 0
java -jar engine/Tron.jar maps/test-board2.txt "./MyTronBot"  "java -jar example_bots/RunAway.jar" 0
java -jar engine/Tron.jar maps/test-board2.txt "./MyTronBot"  "java -jar example_bots/WallHugger.jar" 0
java -jar engine/Tron.jar maps/test-board.txt "./MyTronBot"  "java -jar example_bots/Chaser.jar" 0
java -jar engine/Tron.jar maps/test-board.txt "./MyTronBot"  "java -jar example_bots/RandomBot.jar" 0
java -jar engine/Tron.jar maps/test-board.txt "./MyTronBot"  "java -jar example_bots/RunAway.jar" 0
java -jar engine/Tron.jar maps/test-board.txt "./MyTronBot"  "java -jar example_bots/WallHugger.jar" 0
java -jar engine/Tron.jar maps/toronto.txt "./MyTronBot"  "java -jar example_bots/Chaser.jar" 0
java -jar engine/Tron.jar maps/toronto.txt "./MyTronBot"  "java -jar example_bots/RandomBot.jar" 0
java -jar engine/Tron.jar maps/toronto.txt "./MyTronBot"  "java -jar example_bots/RunAway.jar" 0
java -jar engine/Tron.jar maps/toronto.txt "./MyTronBot"  "java -jar example_bots/WallHugger.jar" 0
java -jar engine/Tron.jar maps/trix.txt "./MyTronBot"  "java -jar example_bots/Chaser.jar" 0
java -jar engine/Tron.jar maps/trix.txt "./MyTronBot"  "java -jar example_bots/RandomBot.jar" 0
java -jar engine/Tron.jar maps/trix.txt "./MyTronBot"  "java -jar example_bots/RunAway.jar" 0
java -jar engine/Tron.jar maps/trix.txt "./MyTronBot"  "java -jar example_bots/WallHugger.jar" 0
java -jar engine/Tron.jar maps/u.txt "./MyTronBot"  "java -jar example_bots/Chaser.jar" 0
java -jar engine/Tron.jar maps/u.txt "./MyTronBot"  "java -jar example_bots/RandomBot.jar" 0
java -jar engine/Tron.jar maps/u.txt "./MyTronBot"  "java -jar example_bots/RunAway.jar" 0
java -jar engine/Tron.jar maps/u.txt "./MyTronBot"  "java -jar example_bots/WallHugger.jar" 0
